<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dovera.AI.MCP.Abstractions/Dovera.AI.MCP.Abstractions.csproj" />
    <ProjectReference Include="../Dovera.AI.MCP.External.PublicReporting/Dovera.AI.MCP.External.PublicReporting.csproj" />
    <ProjectReference Include="../Dovera.AI.MCP.Interanal.FinancialConfidentialData/Dovera.AI.MCP.Interanal.FinancialConfidentialData.csproj" />
  </ItemGroup>
</Project>
